name: Update

on:
  workflow_dispatch:
    inputs:
      version_code:
        required: true
        type: string

      version_tag:
        type: string

env:
  PACKAGE_NAME: xray-core
  CACHE_DIR: ~/cache

jobs:
  update:
    name: Update new version
    runs-on: ubuntu-latest
    steps:
      - name: 'Check Source code version'
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 2

      - name: 'Upadate Makefile' 
        run: |
          DEBIAN_FRONTEND=noninteractive \
          sh ./update.sh ${{ inputs.version_code }} ${{ inputs.version_tag }}

      - name: Deploy Package Source
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: main
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ inputs.version_code }}
